language: ruby
sudo: false
install: bundle install --without development --jobs=3 --retry=3
cache:
  directories:
  - bundle
branches:
  only:
  - build
rvm:
  - 2.3.0
before_script:
- git config --global user.email "root@olisti.co"
- git config --global user.name "Maurizio De Magnis"
- git remote rm origin
- git remote add origin https://olistik:${GH_TOKEN}@github.com/olistik/build-tests.git
- mkdir build
script:
- bundle exec ruby bin/build && bundle exec middleman deploy
